test_that("execution stamps reject changed inputs, outputs and missing products", {
  root <- withr::local_tempdir()
  input <- file.path(root, "input.txt")
  output <- file.path(root, "output.txt")
  stamp <- file.path(root, "stamp.rds")
  readr::write_lines("input", input)
  readr::write_lines("result", output)
  signature <- execution_signature(list(seed = 1), input)
  expect_false(execution_current(stamp, signature, output))
  write_execution_stamp(stamp, signature, output)
  expect_true(execution_current(stamp, signature, output))
  expect_false(execution_current(stamp, execution_signature(list(seed = 2), input), output))
  readr::write_lines("changed input", input)
  expect_false(execution_current(stamp, execution_signature(list(seed = 1), input), output))
  readr::write_lines("changed output", output)
  expect_false(execution_current(stamp, signature, output))
  expect_false(execution_current(stamp, signature, file.path(root, "missing")))
})

test_that("new result directories are allowed but links are read-only", {
  root <- withr::local_tempdir()
  expect_no_error(assert_unlinked_result(file.path(root, "not-created")))
  existing <- file.path(root, "existing")
  dir.create(existing)
  expect_no_error(assert_unlinked_result(existing))
  link <- file.path(root, "linked")
  expect_true(file.symlink(existing, link))
  expect_error(assert_unlinked_result(link), "linked LDAK")
})
