# Generate portable, analysis-local LDAK execution scripts.

shell_quote <- function(x) {
  paste0("'", gsub("'", "'\\\"'\\\"'", x, fixed = TRUE), "'")
}

ldak_job_specs <- function(config) {
  paths <- analysis_paths(config)
  list(
    enhancer = list(
      annotation = file.path(paths[["ldak_annotations"]], "enhancers.loc"),
      output = file.path(paths[["ldak_results"]], ldak_result_subdir(config, "enhancer"))
    ),
    promoter = list(
      annotation = file.path(paths[["ldak_annotations"]], "promoters.loc"),
      output = file.path(paths[["ldak_results"]], ldak_result_subdir(config, "promoter"))
    )
  )
}

project_relative_value <- function(config, path) {
  root <- normalizePath(config$project_root, mustWork = FALSE)
  path <- normalizePath(path, mustWork = FALSE)
  prefix <- paste0(root, .Platform$file.sep)
  if (startsWith(path, prefix)) {
    return(substring(path, nchar(prefix) + 1L))
  }
  path
}

make_ldak_job_lines <- function(config, node_type, annotation, output) {
  project_root_value <- config$project$root
  if (is_absolute_path(project_root_value)) {
    project_root_line <- paste0("PROJECT_ROOT=", shell_quote(normalizePath(config$project_root, mustWork = FALSE)))
  } else {
    project_root_line <- paste0(
      "PROJECT_ROOT=\"$(cd \"${ANALYSIS_ROOT}/", project_root_value, "\" && pwd)\""
    )
  }
  relative <- function(path) project_relative_value(config, path)
  # Preserve the configured spelling of the executable path so a local link in
  # analysis1 remains visible in generated scripts rather than being resolved
  # to its target by normalizePath().
  configured_ldak_exe <- config$reference$ldak_exe
  ldak_exe_line <- if (is_absolute_path(configured_ldak_exe)) {
    paste0("LDAK_EXE=", shell_quote(configured_ldak_exe))
  } else {
    paste0("LDAK_EXE=\"${PROJECT_ROOT}/", configured_ldak_exe, "\"")
  }
  bfile <- relative(resolve_config_path(config$reference$bfile_prefix, config$project_root))
  summary_file <- relative(resolve_config_path(config$gwas$summary_file, config$project_root))
  pvalue_file <- relative(resolve_config_path(config$gwas$pvalue_file, config$project_root))
  extract_file <- relative(resolve_config_path(config$gwas$extract_file, config$project_root))
  input_assignment <- function(name, value) {
    if (is_absolute_path(value)) paste0(name, "=", shell_quote(value)) else
      paste0(name, "=\"${PROJECT_ROOT}/", value, "\"")
  }
  annotation_relative <- substring(annotation, nchar(analysis_paths(config)[["root"]]) + 2L)
  output_relative <- substring(output, nchar(analysis_paths(config)[["root"]]) + 2L)
  threads <- as.integer(config$ldak$threads %||% 1L)
  continuation <- "\\"

  c(
    "#!/usr/bin/env bash",
    paste0("# Generated by hotnetR2 for ", config$analysis$name, " (", node_type, ")"),
    "# This script is suitable for direct bash execution or Slurm submission.",
    paste0("#SBATCH --job-name=LDAK_", config$analysis$name, "_", node_type),
    paste0("#SBATCH --time=", config$slurm$time %||% "12:00:00"),
    "#SBATCH --nodes=1",
    paste0("#SBATCH --cpus-per-task=", threads),
    paste0("#SBATCH --mem=", config$slurm$memory %||% "16G"),
    paste0("#SBATCH --partition=", config$slurm$partition %||% "general-compute"),
    paste0("#SBATCH --qos=", config$slurm$qos %||% "general-compute"),
    "#SBATCH --output=%x_%j.log",
    "",
    "set -euo pipefail",
    "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
    "ANALYSIS_ROOT=\"$(cd \"${SCRIPT_DIR}/../..\" && pwd)\"",
    project_root_line,
    ldak_exe_line,
    input_assignment("BFILE_REF", bfile),
    input_assignment("SUMMARY_STATS", summary_file),
    input_assignment("PVALUES_FILE", pvalue_file),
    input_assignment("EXTRACT_FILE", extract_file),
    paste0("ANNOT_FILE=\"${ANALYSIS_ROOT}/", annotation_relative, "\""),
    paste0("OUT_PREFIX=\"${ANALYSIS_ROOT}/", output_relative, "\""),
    paste0("THREADS=${SLURM_CPUS_PER_TASK:-", threads, "}"),
    "",
    "for required in \"$LDAK_EXE\" \"${BFILE_REF}.bed\" \"${BFILE_REF}.bim\" \"${BFILE_REF}.fam\" \"$ANNOT_FILE\" \"$SUMMARY_STATS\" \"$PVALUES_FILE\" \"$EXTRACT_FILE\"; do",
    "  [[ -f \"$required\" ]] || { echo \"Missing input: $required\" >&2; exit 1; }",
    "done",
    "mkdir -p \"$(dirname \"$OUT_PREFIX\")\"",
    "",
    "echo 'Step 1/3: partition SNPs into regions'",
    paste0('"$LDAK_EXE" --cut-genes "$OUT_PREFIX" ', continuation),
    paste0('  --bfile "$BFILE_REF" --extract "$EXTRACT_FILE" ', continuation),
    paste0("  --genefile \"$ANNOT_FILE\" --gene-buffer ",
           ldak_flank_bp(config, node_type), " --pvalues \"$PVALUES_FILE\""),
    "",
    "echo 'Step 2/3: calculate region REML statistics'",
    paste0('"$LDAK_EXE" --calc-genes-reml "$OUT_PREFIX" ', continuation),
    paste0('  --summary "$SUMMARY_STATS" --bfile "$BFILE_REF" ', continuation),
    paste0("  --ignore-weights ", if (isTRUE(config$ldak$ignore_weights)) "YES" else "NO",
           " --allow-ambiguous ", if (isTRUE(config$ldak$allow_ambiguous)) "YES" else "NO", " ", continuation),
    paste0("  --power ", config$ldak$power, " --gene-prune ", config$ldak$pruning, " ", continuation),
    paste0("  --gene-permutations ", as.integer(config$ldak$permutations), " --extract \"$EXTRACT_FILE\" ", continuation),
    paste0("  --random-seed ", as.integer(config$analysis$random_seed), " --max-threads \"$THREADS\""),
    "",
    "echo 'Step 3/3: join REML results'",
    "\"$LDAK_EXE\" --join-genes-reml \"$OUT_PREFIX\"",
    "echo \"Complete: ${OUT_PREFIX}/remls.all\""
  )
}

#' Generate local/Slurm LDAK job scripts
#'
#' The generated scripts write results only under `analysis1/LDAK/results` and
#' locate external resources through `PROJECT_ROOT`, derived from the
#' configuration. They do not submit jobs.
#'
#' @param config A configuration returned by [read_analysis_config()].
#' @param dry_run If `TRUE`, return planned script paths without writing them.
#' @return Named paths of enhancer and promoter scripts.
#' @export
generate_ldak_jobs <- function(config, dry_run = TRUE) {
  specs <- ldak_job_specs(config)
  paths <- analysis_paths(config)
  script_paths <- file.path(paths[["ldak_scripts"]], paste0("run_ldak_", names(specs), ".sh"))
  names(script_paths) <- names(specs)
  if (isTRUE(dry_run)) return(script_paths)

  dir.create(paths[["ldak_scripts"]], recursive = TRUE, showWarnings = FALSE)
  for (node_type in names(specs)) {
    lines <- make_ldak_job_lines(config, node_type, specs[[node_type]]$annotation, specs[[node_type]]$output)
    writeLines(lines, script_paths[[node_type]])
    Sys.chmod(script_paths[[node_type]], mode = "0755")
  }
  script_paths
}

#' Generate a direct local LDAK runner
#'
#' The runner executes selected generated enhancer/promoter scripts sequentially
#' with `bash`; it has no `sbatch` call and therefore works on the local macOS
#' machine through the configured `analysis1/ldak6.2.mac` link. With no
#' arguments it runs both; command-line arguments can select one or both.
#'
#' @param config A configuration returned by [read_analysis_config()].
#' @param dry_run If `TRUE`, return the planned runner path without writing it.
#' @return Path to the local runner.
#' @export
generate_ldak_local_runner <- function(config, dry_run = TRUE) {
  path <- file.path(analysis_paths(config)[["ldak_scripts"]], "run_ldak_local.sh")
  if (isTRUE(dry_run)) return(path)
  script_paths <- generate_ldak_jobs(config, dry_run = FALSE)
  lines <- c(
    "#!/usr/bin/env bash",
    "# Run both analysis1 LDAK analyses sequentially on the local machine.",
    "# This script does not call sbatch or require a Slurm environment.",
    "set -euo pipefail",
    "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
    "NODE_TYPES=(enhancer promoter)",
    "if (( $# > 0 )); then NODE_TYPES=(\"$@\"); fi",
    "for node_type in \"${NODE_TYPES[@]}\"; do",
    "  case \"$node_type\" in enhancer|promoter) ;; *) echo \"Unknown LDAK node type: $node_type\" >&2; exit 2 ;; esac",
    "  bash \"${SCRIPT_DIR}/run_ldak_${node_type}.sh\"",
    "done"
  )
  writeLines(lines, path)
  Sys.chmod(path, mode = "0755")
  path
}
