# Generate an analysis-local hierarchical HotNet execution wrapper.

make_hhotnet_job_lines <- function(config, networks = NULL) {
  paths <- analysis_paths(config)
  execution_mode <- config$hhotnet$execution_mode %||% "apptainer"
  if (!execution_mode %in% c("apptainer", "local_python")) {
    stop("hhotnet.execution_mode must be apptainer or local_python", call. = FALSE)
  }
  if (identical(execution_mode, "local_python") && is.null(config$hhotnet$local_dir)) {
    stop("hhotnet.local_dir is required for local_python execution", call. = FALSE)
  }
  project_root_value <- config$project$root
  project_root_line <- if (is_absolute_path(project_root_value)) {
    paste0("PROJECT_ROOT=", shell_quote(normalizePath(config$project_root, mustWork = FALSE)))
  } else {
    paste0("PROJECT_ROOT=\"$(cd \"${ANALYSIS_ROOT}/", project_root_value, "\" && pwd)\"")
  }
  networks <- resolve_networks(config, networks)
  network_words <- paste(networks, collapse = " ")
  image <- config$hhotnet$apptainer_image
  if (!is_absolute_path(image)) image <- project_relative_value(config, resolve_config_path(image, config$project_root))
  image_line <- if (is_absolute_path(image)) {
    paste0("DEFAULT_IMAGE=", shell_quote(image))
  } else {
    paste0("DEFAULT_IMAGE=\"${PROJECT_ROOT}/", image, "\"")
  }
  local_dir <- if (is.null(config$hhotnet$local_dir)) "" else resolve_config_path(config$hhotnet$local_dir, config$project_root)
  python_executable <- config$hhotnet$python_executable %||% "python3"
  compat_dir <- config$hhotnet$compat_dir %||% file.path(analysis_paths(config)[["hhotnet"]], "compat")
  compat_dir <- resolve_config_path(compat_dir, config$project_root)
  c(
    "#!/usr/bin/env bash",
    paste0("# Generated by hotnetR2 for ", config$analysis$name),
    "# Run directly with bash, or submit this one script to Slurm. It never submits itself.",
    paste0("#SBATCH --job-name=hhotnet_", config$analysis$name),
    paste0("#SBATCH --time=", config$slurm$time %||% "72:00:00"),
    "#SBATCH --nodes=1",
    paste0("#SBATCH --cpus-per-task=", as.integer(config$hhotnet$cpus)),
    "#SBATCH --mem=128G",
    paste0("#SBATCH --partition=", config$slurm$partition %||% "general-compute"),
    paste0("#SBATCH --qos=", config$slurm$qos %||% "general-compute"),
    "#SBATCH --output=%x_%j.log",
    "",
    "set -euo pipefail",
    "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
    "ANALYSIS_ROOT=\"$(cd \"${SCRIPT_DIR}/../..\" && pwd)\"",
    project_root_line,
    image_line,
    paste0("DEFAULT_MODE=", shell_quote(execution_mode)),
    paste0("DEFAULT_HHOTNET_DIR=", shell_quote(local_dir)),
    paste0("DEFAULT_PYTHON=", shell_quote(python_executable)),
    paste0("DEFAULT_COMPAT_DIR=", shell_quote(compat_dir)),
    "MODE=\"${HHOTNET_EXECUTION_MODE:-$DEFAULT_MODE}\"",
    "HHOTNET_DIR=\"${HHOTNET_LOCAL_DIR:-$DEFAULT_HHOTNET_DIR}\"",
    "PYTHON_BIN=\"${HHOTNET_PYTHON:-$DEFAULT_PYTHON}\"",
    "COMPAT_DIR=\"${HHOTNET_COMPAT_DIR:-$DEFAULT_COMPAT_DIR}\"",
    "IMAGE=\"${HHOTNET_IMAGE:-$DEFAULT_IMAGE}\"",
    paste0("SCORE_NAME=\"${HHOTNET_SCORE_NAME:-", config$hhotnet$score_name, "}\""),
    paste0("NUM_PERMUTATIONS=\"${HHOTNET_NUM_PERMUTATIONS:-", as.integer(config$hhotnet$num_permutations), "}\""),
    paste0("PERMUTATION_SEED=\"${HHOTNET_PERMUTATION_SEED:-", as.integer(config$hhotnet$permutation_seed %||% 0L), "}\""),
    paste0("LOWER_SIZE_BOUND=\"${HHOTNET_LOWER_SIZE_BOUND:-", as.integer(config$hhotnet$lower_size_bound), "}\""),
    paste0("CPUS=\"${SLURM_CPUS_PER_TASK:-${HHOTNET_CPUS:-", as.integer(config$hhotnet$cpus), "}}\""),
    paste0("DEFAULT_NETWORKS=(", network_words, ")"),
    "DATA_DIR=\"${ANALYSIS_ROOT}/hHotnet/data\"",
    "INTERMEDIATE_DIR=\"${ANALYSIS_ROOT}/hHotnet/intermediate\"",
    "RESULTS_DIR=\"${ANALYSIS_ROOT}/hHotnet/results\"",
    "LOG_DIR=\"${ANALYSIS_ROOT}/logs\"",
    "STATUS_DIR=\"${ANALYSIS_ROOT}/hHotnet/summary/status\"",
    "",
    "if [[ \"$MODE\" == \"local_python\" ]]; then",
    "  [[ -d \"${HHOTNET_DIR}/src\" ]] || { echo \"Missing local Hierarchical HotNet source: $HHOTNET_DIR\" >&2; exit 1; }",
    "  command -v \"$PYTHON_BIN\" >/dev/null 2>&1 || { echo \"Missing Python executable: $PYTHON_BIN\" >&2; exit 1; }",
    "  [[ -d \"$COMPAT_DIR\" ]] || { echo \"Missing Hierarchical HotNet compatibility directory: $COMPAT_DIR\" >&2; exit 1; }",
    "  export PYTHONPATH=\"${COMPAT_DIR}${PYTHONPATH:+:${PYTHONPATH}}\"",
    "  export MPLCONFIGDIR=\"${ANALYSIS_ROOT}/hHotnet/.matplotlib\"",
    "  export XDG_CACHE_HOME=\"${ANALYSIS_ROOT}/hHotnet/.cache\"",
    "  mkdir -p \"$MPLCONFIGDIR\" \"$XDG_CACHE_HOME\"",
    "elif [[ \"$MODE\" == \"apptainer\" ]]; then",
    "  command -v apptainer >/dev/null 2>&1 || { echo 'Missing apptainer executable' >&2; exit 1; }",
    "  [[ -f \"$IMAGE\" ]] || { echo \"Missing h-HotNet image: $IMAGE\" >&2; exit 1; }",
    "else",
    "  echo \"Unsupported h-HotNet execution mode: $MODE\" >&2; exit 2",
    "fi",
    "NETWORKS=(\"${DEFAULT_NETWORKS[@]}\")",
    "if (( $# > 0 )); then NETWORKS=(\"$@\"); fi",
    "for network in \"${NETWORKS[@]}\"; do",
    paste0("  case \"$network\" in ", paste(networks, collapse = "|"), ") ;; *) echo \"Unknown or unconfigured network: $network\" >&2; exit 2 ;; esac"),
    "done",
    "mkdir -p \"$INTERMEDIATE_DIR\" \"$RESULTS_DIR\" \"$LOG_DIR\" \"$STATUS_DIR\"",
    "write_status() {",
    "  local network=\"$1\" stage=\"$2\" status=\"$3\" detail=\"${4:-}\" file=\"${STATUS_DIR}/$1.tsv\"",
    "  [[ -f \"$file\" ]] || printf 'timestamp_utc\\tnetwork\\tstage\\tstatus\\tdetail\\n' > \"$file\"",
    "  printf '%s\\t%s\\t%s\\t%s\\t%s\\n' \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\" \"$network\" \"$stage\" \"$status\" \"$detail\" >> \"$file\"",
    "}",
    "acquire_lock() {",
    "  local lock=\"$1\" holder=\"\"",
    "  if mkdir \"$lock\" 2>/dev/null; then printf '%s\\n' \"$$\" > \"${lock}/pid\"; return 0; fi",
    "  [[ -f \"${lock}/pid\" ]] && holder=\"$(cat \"${lock}/pid\")\"",
    "  echo \"Network is already running (lock: ${lock}; pid: ${holder:-unknown})\" >&2",
    "  return 1",
    "}",
    "release_lock() { [[ -n \"${1:-}\" ]] && { rm -f \"$1/pid\"; rmdir \"$1\" 2>/dev/null || true; }; }",
    "on_error() { local code=$?; [[ -n \"${CURRENT_LOCK:-}\" ]] && release_lock \"$CURRENT_LOCK\"; [[ -n \"${network:-}\" ]] && write_status \"$network\" failed \"$code\" \"${CURRENT_LOG:-}\"; exit \"$code\"; }",
    "trap on_error ERR",
    "run_hhotnet() {",
    "  if [[ \"$MODE\" == \"local_python\" ]]; then \"$PYTHON_BIN\" \"${HHOTNET_DIR}/src/$1\" \"${@:2}\" >> \"$CURRENT_LOG\" 2>&1; else apptainer exec \"$IMAGE\" \"$@\" >> \"$CURRENT_LOG\" 2>&1; fi",
    "}",
    "",
    "for network in \"${NETWORKS[@]}\"; do",
    "  network_intermediate=\"${INTERMEDIATE_DIR}/${network}\"",
    "  score_intermediate=\"${INTERMEDIATE_DIR}/${network}_${SCORE_NAME}\"",
    "  network_results=\"${RESULTS_DIR}/${network}\"",
    "  edge_file=\"${DATA_DIR}/${network}_edge_list.tsv\"",
    "  index_file=\"${DATA_DIR}/${network}_index_gene.tsv\"",
    "  score_file=\"${DATA_DIR}/${SCORE_NAME}.tsv\"",
    "  for required in \"$edge_file\" \"$index_file\" \"$score_file\"; do [[ -f \"$required\" ]] || { echo \"Missing input: $required\" >&2; exit 1; }; done",
    "  mkdir -p \"$network_intermediate\" \"$score_intermediate\" \"$network_results\"",
    "  CURRENT_LOCK=\"${network_intermediate}/.run_lock\"",
    "  if ! acquire_lock \"$CURRENT_LOCK\"; then write_status \"$network\" run locked \"$CURRENT_LOCK\"; exit 75; fi",
    "  CURRENT_LOG=\"${LOG_DIR}/${network}_${SCORE_NAME}.log\"",
    "  write_status \"$network\" preflight started \"$CURRENT_LOG\"",
    "  if [[ ! -f \"${network_intermediate}/similarity_matrix.h5\" ]]; then",
    "    write_status \"$network\" similarity_matrix running",
    "    run_hhotnet construct_similarity_matrix.py -i \"$edge_file\" -o \"${network_intermediate}/similarity_matrix.h5\" -bof \"${network_intermediate}/beta.txt\"",
    "    write_status \"$network\" similarity_matrix complete",
    "  fi",
    "  cp \"$score_file\" \"${score_intermediate}/scores_0.tsv\"",
    "  if [[ ! -f \"${score_intermediate}/score_bins.tsv\" ]]; then",
    "    write_status \"$network\" score_bins running",
    "    run_hhotnet find_permutation_bins.py -gsf \"${score_intermediate}/scores_0.tsv\" -igf \"$index_file\" -elf \"$edge_file\" -ms 1000 -o \"${score_intermediate}/score_bins.tsv\"",
    "    write_status \"$network\" score_bins complete",
    "  fi",
    "  missing_scores=()",
    "  for i in $(seq 1 \"$NUM_PERMUTATIONS\"); do [[ -s \"${score_intermediate}/scores_${i}.tsv\" ]] || missing_scores+=(\"$i\"); done",
    "  if (( ${#missing_scores[@]} )); then",
    "    write_status \"$network\" score_permutations running \"missing=${#missing_scores[@]}\"",
    "  if [[ \"$MODE\" == \"local_python\" ]]; then",
    "    printf '%s\\n' \"${missing_scores[@]}\" | xargs -I{} -P \"$CPUS\" bash -c '\"$1\" \"$2\" -i \"$3\" -bf \"$4\" -s \"$(( $5 + $0 ))\" -o \"$6/scores_${0}.tsv\"' {} \"$PYTHON_BIN\" \"${HHOTNET_DIR}/src/permute_scores.py\" \"${score_intermediate}/scores_0.tsv\" \"${score_intermediate}/score_bins.tsv\" \"$PERMUTATION_SEED\" \"$score_intermediate\" >> \"$CURRENT_LOG\" 2>&1",
    "  else",
    "    printf '%s\\n' \"${missing_scores[@]}\" | xargs -I{} -P \"$CPUS\" apptainer exec \"$IMAGE\" permute_scores.py -i \"${score_intermediate}/scores_0.tsv\" -bf \"${score_intermediate}/score_bins.tsv\" -s {} -o \"${score_intermediate}/scores_{}.tsv\" >> \"$CURRENT_LOG\" 2>&1",
    "  fi",
    "    write_status \"$network\" score_permutations complete",
    "  fi",
    "  missing_hierarchies=()",
    "  for i in $(seq 0 \"$NUM_PERMUTATIONS\"); do [[ -s \"${score_intermediate}/hierarchy_edge_list_${i}.tsv\" && -s \"${score_intermediate}/hierarchy_index_gene_${i}.tsv\" ]] || missing_hierarchies+=(\"$i\"); done",
    "  if (( ${#missing_hierarchies[@]} )); then",
    "    write_status \"$network\" hierarchies running \"missing=${#missing_hierarchies[@]}\"",
    "    if [[ \"$MODE\" == \"local_python\" ]]; then",
    "      printf '%s\\n' \"${missing_hierarchies[@]}\" | xargs -I{} -P \"$CPUS\" \"$PYTHON_BIN\" \"${HHOTNET_DIR}/src/construct_hierarchy.py\" -smf \"${network_intermediate}/similarity_matrix.h5\" -igf \"$index_file\" -gsf \"${score_intermediate}/scores_{}.tsv\" -helf \"${score_intermediate}/hierarchy_edge_list_{}.tsv\" -higf \"${score_intermediate}/hierarchy_index_gene_{}.tsv\" >> \"$CURRENT_LOG\" 2>&1",
    "    else",
    "      printf '%s\\n' \"${missing_hierarchies[@]}\" | xargs -I{} -P \"$CPUS\" apptainer exec \"$IMAGE\" construct_hierarchy.py -smf \"${network_intermediate}/similarity_matrix.h5\" -igf \"$index_file\" -gsf \"${score_intermediate}/scores_{}.tsv\" -helf \"${score_intermediate}/hierarchy_edge_list_{}.tsv\" -higf \"${score_intermediate}/hierarchy_index_gene_{}.tsv\" >> \"$CURRENT_LOG\" 2>&1",
    "    fi",
    "    write_status \"$network\" hierarchies complete",
    "  fi",
    "  permuted_edge_lists=(); permuted_index_files=()",
    "  for i in $(seq 1 \"$NUM_PERMUTATIONS\"); do permuted_edge_lists+=(\"${score_intermediate}/hierarchy_edge_list_${i}.tsv\"); permuted_index_files+=(\"${score_intermediate}/hierarchy_index_gene_${i}.tsv\"); done",
    "  if [[ ! -s \"${network_results}/clusters_${network}_${SCORE_NAME}.tsv\" ]]; then",
    "    write_status \"$network\" process_hierarchies running",
    "    run_hhotnet process_hierarchies.py -oelf \"${score_intermediate}/hierarchy_edge_list_0.tsv\" -oigf \"${score_intermediate}/hierarchy_index_gene_0.tsv\" -pelf \"${permuted_edge_lists[@]}\" -pigf \"${permuted_index_files[@]}\" -lsb \"$LOWER_SIZE_BOUND\" -cf \"${network_results}/clusters_${network}_${SCORE_NAME}.tsv\" -pl \"$network\" \"$SCORE_NAME\" -pf \"${network_results}/sizes_${network}_${SCORE_NAME}.pdf\" -nc \"$CPUS\"",
    "    write_status \"$network\" process_hierarchies complete",
    "  fi",
    "  write_status \"$network\" run complete \"${network_results}/clusters_${network}_${SCORE_NAME}.tsv\"",
    "  release_lock \"$CURRENT_LOCK\"",
    "  CURRENT_LOCK=\"\"",
    "done"
  )
}

#' Generate a hierarchical HotNet execution wrapper
#'
#' The wrapper writes only inside `analysis1/hHotnet` and can be run locally or
#' submitted manually. Generating it never runs Apptainer or submits a job.
#'
#' @param config A configuration returned by [read_analysis_config()].
#' @param networks `NULL` for the configured default, one network name, or a
#'   vector of network names. The generated wrapper can also accept one or more
#'   network names as command-line arguments at execution time.
#' @param dry_run If `TRUE`, return the planned script path without writing it.
#' @return Path to the executable wrapper.
#' @export
generate_hhotnet_job <- function(config, networks = NULL, dry_run = TRUE) {
  resolve_networks(config, networks)
  path <- file.path(analysis_paths(config)[["hhotnet_scripts"]], "run_hhotnet.sh")
  if (isTRUE(dry_run)) return(path)
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(make_hhotnet_job_lines(config, networks = networks), path)
  Sys.chmod(path, mode = "0755")
  path
}
